### ISSUE TITLE
Need a way to strip MS Word Formatting when people copy from Word and paste.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/lrnwebcomponents#101]
Copying from word and pasting adds the MS Word formatting and while someone could use the paste without formatting browser options, the problem is that it's not inherently intuitive for the people who would copy and paste from word.

**Comment by btopro** [comment]
this is an enhancements for.....?

**Comment by btopro** [comment]
this does not occur on haxtheweb.org as I believe this issue was solved in a sanitization of javascript issue that was fixed just before the work on ES modules started
