### ISSUE TITLE
[hax]New paragraph via return fails

### ISSUE THREAD

**Issue by aitala** [elmsln/lrnwebcomponents#167]
For Safari and Firefox on MacOS, the creation of a new has paragraph block after hitting return does not function properly.

For Safari, a return does nothing.  No new block is created.

For Firefox using the codepen page, a return generates a new block, but the page scrolls past it and opens the menu bar.  To add text, you have to scroll up.  I'm not sure if this is a HAX issue or a codepen issue. 

See Image

<img width="754" alt="screen shot 2019-01-22 at 9 37 18 am" src="https://user-images.githubusercontent.com/4474470/51542638-b7f09300-1e29-11e9-886d-6e2d5aa7a3d0.png">

**Comment by btopro** [comment]
First might be safari being stupid, second sounds like code pen but I'll have to check. Weird stuff happens in codepen js

**Comment by aitala** [comment]
Yeah, that makes sense for both.  Is haxtheweb.org updated with the newest WCs? I can test there to remove Codepen as a culprit.

**Comment by btopro** [comment]
no, current sprint is to have the world in shape for doing that site right via HAXCMS

**Comment by btopro** [comment]
you can git clone the repo, then run `yarn install` from the directory then `cd elements/h-a-x` and run `yarn start` to get a local demo

**Comment by aitala** [comment]
Ok, in MacOS Firefox, a return creates a new <P> block, but the cursor does not appear in the new <P>.  You have to manually click into the block to start adding text. And even then, no editing '|' type cursor appears. See Image Below

In Safari, a return does nothing within a <P>.

<img width="533" alt="screen shot 2019-01-22 at 10 39 39 am" src="https://user-images.githubusercontent.com/4474470/51546432-20437280-1e32-11e9-8ee0-6e16dc643386.png">

**Comment by btopro** [comment]
wait.. .you have to manually do something!? THIS IS UNACCEPTABLE
