### ISSUE TITLE
change calls to pathFromUrl(import.meta.url) to include decodeURIComponent

### ISSUE THREAD

**Issue by CoLdAs1cE** [elmsln/lrnwebcomponents#203]
when trying to use it changes @ to %40 (when trying to use firebase serve)
when it trys to import openseadragon from

```javascript
created: function() {
    const name = "openseadragon";
    const basePath = pathFromUrl(import.meta.url);
    const location = `${basePath}lib/openseadragon/build/openseadragon/openseadragon.js`;
    window.addEventListener(
      `es-bridge-${name}-loaded`,
      this._openseadragonLoaded.bind(this)
    );
    window.ESGlobalBridge.requestAvailability();
    window.ESGlobalBridge.instance.load(name, location);
},
```

and build it using @lrnwebcomponents/img-pan-zoom 2.0.2

**Comment by btopro** [comment]
I'm not following. Do you mean you can't use this specific library or any of them? img-pan-zoom uses openseadragon which isn't available as ESM compatible libary so this bridge helper it's using ensures a promise makes the element work while knowing the library has been loaded into global scope correctly.

Are you NOT using this element yet it's interfering with a polymer build routine?

**Comment by CoLdAs1cE** [comment]
sorry for bad explanation, I WANT TO USE It
BUT I CANT AFter i polymer build the path becomes

%40lrnwebcomponents/img-pan-zoom/lib/openseadragon etc.

and i cannot serve that path it trows error and cannot find module. so i cannot use this nice component
but it works when not built, so i changed ${basePath}. and hardcoded the node_module path then it works, so when polymer build, built it. it changes this path because its to dynamic or something. i think this is culprit **const basePath = pathFromUrl(import.meta.url);** mby u need to url decode or something

**Comment by btopro** [comment]
hmmm... are you on a PC or something? Here's the polymer.json that I use for building this correctly:
```
"extraDependencies": [
    "manifest.json",
    "node_modules/@lrnwebcomponents/*/*.js",
    "node_modules/@lrnwebcomponents/*/lib/*",
    "node_modules/@lrnwebcomponents/*/lib/*/*",
    "node_modules/@polymer/app-layout/*/*.js",
    "node_modules/@lrnwebcomponents/img-pan-zoom/lib/openseadragon/build/openseadragon/openseadragon.js",
    "node_modules/@lrnwebcomponents/elmsln-apps/lib/*/*.js",
    "node_modules/@lrnwebcomponents/lrn-calendar/lib/ical.js/build/ical.js",
    "node_modules/@lrnwebcomponents/wave-player/lib/wavesurfer.js/dist/wavesurfer.js",
    "!node_modules/@lrnwebcomponents/*/*.story.js",
    "node_modules/@webcomponents/webcomponentsjs/*.js",
    "!node_modules/@webcomponents/webcomponentsjs/gulpfile.js",
    "node_modules/@webcomponents/webcomponentsjs/bundles/*.js",
    "node_modules/monaco-editor/min/**"
  ],
```

note the openseadragon library direct inclusion -- https://github.com/elmsln/haxcms/blob/master/polymer.json

**Comment by CoLdAs1cE** [comment]
when i try to firebase serve it. it wont allow me cuz path is invalid as i explained above

**Comment by btopro** [comment]
interesting. Ok, I'll update the title to reflect this and see what we can do

**Comment by btopro** [comment]
ok fixed in master. doing a build and then I'll publish new versions so they all get it (we use that convention in like 10 places so good to rebuild).

Thanks for help tracking this down, hopefully the republish helps

**Comment by CoLdAs1cE** [comment]
ill find out on Thursday. thanks for fix!

**Comment by btopro** [comment]
2.0.6 is published https://www.npmjs.com/package/@lrnwebcomponents/img-pan-zoom
