### ISSUE TITLE
[video-player / a11y-media] Youtube autoplays like 1 second sometimes

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#213]
https://haxtheweb.org/ check it on home page.

@nikkimk

**Comment by nikkimk** [comment]
It has to. The only way to be able to seek show the length of a video is to let it play. The YouTube iframe player API does not provide metadata about the video until it plays. Our only other option would be to disable everything but the play button until it loads.

**Comment by btopro** [comment]
hm.. cause autoplaying video is quite the suck, especially on mobile like android where it then places it in your notification tray / disrupts other things playing. I'd say it needs disabled until selected.

**Comment by nikkimk** [comment]
PR #214
