### ISSUE TITLE
Error when trying to use "lrndesign-avatar" webcomponent

### ISSUE THREAD

**Issue by maksimyurkov** [elmsln/lrnwebcomponents#215]
Hello!

I try to apply a component "lrndesign-avatar", but an error appears:

> "TypeError: Failed to resolve module specifier \"@polymer/polymer/polymer-legacy.js\". Relative references must start with either \"/\", \"./\", or \"../\"."

Example: [https://jsbin.com/jihutepolu/edit?html,console,output](https://jsbin.com/jihutepolu/edit?html,console,output)

Or am I doing something wrong?

P.S. Thanks for your components!

**Comment by maksimyurkov** [comment]
Everything is working. (incorrectly loaded component)

**Comment by btopro** [comment]
glad to hear it. For future reference (looking at your jsbin) try using unpkg w/ the `?module` flag -- `https://unpkg.com/@lrnwebcomponents/lrndesign-avatar/lrndesign-avatar.js?module` like this
