### ISSUE TITLE
Simple modal quirks

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#223]
Sizing and styling in a way that ensures it's always entirely visible based on how port. Right now it's kinda wonky and Also sizes to the minimal viewable area which looks wierd when using multiple modals in the same experience that keep shifting sizes dramatically

**Comment by btopro** [comment]
@nikkimk

**Comment by nikkimk** [comment]
There are CSS vars for this:

  height: var(--simple-modal-height, auto);
  width: var(--simple-modal-width, auto);
  min-width: var(--simple-modal-min-width, unset);
  max-width: var(--simple-modal-max-width, unset);
  min-height: var(--simple-modal-min-height, unset);
  max-height: var(--simple-modal-max-height, unset);

Is there a specific instance of this where these variables aren't able to resolve your issue?

**Comment by btopro** [comment]
what is the scope I apply these via? a custom-style block so it's at the top of the document? I use the singleton so there's nothing directly to style
