### ISSUE TITLE
explore making simple-colors more efficient

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#262]
Run a lighthouse test on https://haxtheweb.org and you'll see it say something about unused css. If you look it's dozens of simple-colors variables being applied. I have a feeling that we need a way to have the simple-colors css variables applied globally and only once. While I realize individual elements do need to call for simple colors to use the css vars, these will trickle down through the roots.

Perhaps there's some kind of singleton pattern we can use @nikkimk so that it's only added as a single `<custom-style>` block at the top of the document? I don't honestly know the implication atm but there's no way that 78 definitions of `--simple-colors-default-theme-green-6` * all colors is NOT a large area for performance improvement (especially on pages that use a lot of elements).

**Comment by nikkimk** [comment]
`simple-colors` itself does not declare any styles. it just uses `<style is="custom-style" include="simple-colors"></style>`

`simple-colors-styles` is a shared styles element that declares the styles

`simple-colors-styles` and what looks like repetition in there is actually cascading/overriding for styles when accent color and dark change plus all the fact that we have both cssvariables and cssclasses (which i think we don't need) in there

I removed support for the old naming convention and the css classes and performance improved on my end.
