### ISSUE TITLE
Constructable style sheets and hax-body

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#273]
So we need something LIKE constructible style sheets for hax body. I'm not sure this is possible... but we need it. The reason came out of discussions in https://github.com/elmsln/HAXcms/issues/269 and it's the following sticky problem
- hax body supplies some base styles
- these base styles actually become truth if the document above them doesn't supply the styles
- h-a-x is now in a shadowRoot so we need a way of styling things down in things

If we had the ability to put styles into hax-body (kinda like style include="") but constructable style sheets are the future so a dynamic constructable style sheet might work..

**Comment by nikkimk** [comment]
I used them in the latest simple-colors. So let's strategize on adding them to hax-body.

**Comment by btopro** [comment]
@nikkimk you ACTUALLY used constructable stylesheets or you used a very similar technique? If so you've beaten us to the party and will get to explain to the rest how they work :)

**Comment by nikkimk** [comment]
Check our `simple-colors/lib/simple-colors-styles.js`.

**Comment by btopro** [comment]
TypeError: Illegal constructor. in Firefox. That's not a real thing outside of chrome that you just added :)

**Comment by btopro** [comment]
closing for now. There are approaches in motion that mirror aspects of this but it's not a critical thing for us to adopt outright. The changes nikki made are inline with the performance we want and the DOM has stopped locking up so that's all good things :p
