### ISSUE TITLE
Color spectrum and tool use

### ISSUE THREAD

**Issue by beb5040** [elmsln/lrnwebcomponents#277]
![Rainbow Connection](https://user-images.githubusercontent.com/45569686/59881992-0aa18d00-937f-11e9-826c-b90f4c7ad0e8.png)
[Page Link](https://courses.aanda.psu.edu/frnar200/node/17)

Using **Testimonial Boxes**  to establish visible light spectrum  & frequencies et al.

**Comment by btopro** [comment]
thanks for posting this Brendan! I've looked into the next version of HAX and this element doesn't have the floating hyphen when it's not being attributed to someone so this should be fixed when we roll out the next editor

**Comment by btopro** [comment]
@nikkimk --^ check out the thing Brendan made w/ hax :0)
