### ISSUE TITLE
[a11y-media-player] fullscreen button not rendering

### ISSUE THREAD

**Issue by heyMP** [elmsln/lrnwebcomponents#318]
HAXcms version: 0.11.0

A <video-player> rendered in a HAXcms course does not constantly render the full screen icon.  Sometimes if there is only one video on the screen it works but usually if there are multiple videos on a page they don't render.

Example: 
![Screen Shot 2019-08-22 at 8 57 59 AM](https://user-images.githubusercontent.com/3428964/63516493-f848ea00-c4ba-11e9-86f2-98c022177f26.png)

I think I've tracked it down to this function on a11y-media-player https://github.com/elmsln/lrnwebcomponents/blob/master/elements/a11y-media-player/src/a11y-media-player.js#L537-L550

**Comment by btopro** [comment]
@nikkimk deb has brought this up previously

**Comment by nikkimk** [comment]
Fix is in PR #330. LMK if it's still an issue.
