### ISSUE TITLE
new field: fieldset

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#320]
Drupal's got a nice little fieldset capability which just visually groups settings in a larger form / helps provide context. This has a11y enhancements like tabs but without the clicking between capabilities. Also on mobile it's something that could collapse into a single fieldset / gives the user the option to focus and hide settings that might be too much visual clutter in a big list.

I'd imagine this is a simplified version of the tab/tabs methodology. @nikkimk

**Comment by nikkimk** [comment]
See PR #330
