### ISSUE TITLE
new field: markup

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#321]
Drupal has a "markup" field type which is just for injecting HTML bits into forms. This would help with, for example, throwing something like a "DANGER ZONE" under the "git" tab in this screenshot. That'd allow users to put it in context even futher (in this case inside the tab itself) as opposed to having to inject via happy JS scripts elsewhere.
![Uploading 2019-08-22_16-40-59.png…](git settings that would be better if inside the tab with other html elements)

**Comment by nikkimk** [comment]
Included in PR #330
