### ISSUE TITLE
Option to deep link into videos

### ISSUE THREAD

**Issue by kreynen** [elmsln/lrnwebcomponents#340]
One of the features I like about Youtube's out of the box player is the option to deep link a user into a specific point of a video using simple t=timecode querystring like https://youtu.be/FBKlTPcb614?t=318.

Mozilla did a lot of work back with [Popcorn.js](http://www.mozillalabs.com/Popcorn/) to standardize this type of interaction for all the major video streaming providers at the time with anchors, but that project is dead.  I did some work integrating Popcorn with Drupal many years ago with https://www.drupal.org/project/popcorn_chapters

@nikkimk is this possible in the context of the other elements on a page?  Worth the effort?

**Comment by btopro** [comment]
If we uniquely identify the element at run time and assigned a UUID, then made a consistent way for passing run time arguments from URL into elements.. yes.

UUID is easy as our schema behaviors mixin does this automatically. Then we'd need some kind of Singleton that can broker this behavior and pass an event off to any element I. Order to handle parameters. This way you could say uniquely identify tab 5 in a tab list and then inform the tab that it should expand via shared link, or open an image gallery to a specific slide or anything like this but do it in a routerless way to keep it highly modular

**Comment by btopro** [comment]
Or self aware relative heading tags which could provide jump to active heading anchor link style behavior... Damn you late night ideas..

**Comment by nikkimk** [comment]
Will test this when PR #342 is merged.
