### ISSUE TITLE
Hide icons on map menu items without them

### ISSUE THREAD

**Issue by nikkimk** [elmsln/lrnwebcomponents#359]
Map menu items without icons leave an empty space where an icon should be, affecting alignment of menu which makes navigation difficult for the user.

Undefined icons should be hidden.

<img width="1406" alt="Screen Shot 2020-01-06 at 9 56 04 AM" src="https://user-images.githubusercontent.com/5090492/71826320-a1a80b00-306b-11ea-9916-6089e2572aa1.png">

**Comment by btopro** [comment]
you'll have to explain "it makes navigation difficult for the user"

**Comment by btopro** [comment]
fixed
