### ISSUE TITLE
Compatibility With Windows

### ISSUE THREAD

**Issue by McGarvelcuddy** [elmsln/lrnwebcomponents#362]
Symbolic links issue with setting up in Windows
Homework:
- [x] fork the repo nd submit a PR back with the fix #362 
- [x] adjust the documentation to indicate that windows users should configure git end lines correctly (do this in wcfactory AND lrnwebcomponents AND HAXcms repos README.txt while we're at it)
- [x] in this `## Windows notes` area part of the documentation mention Cygwin and provide a link to it
- [x] add symlink-dir to package.json in lrnwebcomponents and wcfactory
- [x] submit PRs to all projects with these changes
- [ ] try to get wcfactory installed and run `wcf start` and see if any issues pop up and submit them

**Comment by btopro** [comment]
links used in solving some of these things.
https://techblog.dorogin.com/case-of-windows-line-ending-in-bash-script-7236f056abe
https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace
https://www.npmjs.com/package/symlink-dir
https://github.com/microsoft/WSL/issues/353
https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

**Comment by btopro** [comment]
@McGarvelcuddy I've created a checklist for your issue as far as what I want you to do for next time.
