### ISSUE TITLE
Postinstall machine checks previous files

### ISSUE THREAD

**Issue by McGarvelcuddy** [elmsln/lrnwebcomponents#369]
Attached are the contents of package.json and postinstall.sh in text files from before the machine checks were added to postinstall.sh.

[package.txt](https://github.com/elmsln/lrnwebcomponents/files/4098747/package.txt)
[postinstall.txt](https://github.com/elmsln/lrnwebcomponents/files/4098748/postinstall.txt)

**Comment by btopro** [comment]
so bizzare that this is still causing issues... looked at the files, didnt see any issues. ugh
