### ISSUE TITLE
Cheat sheet

### ISSUE THREAD

**Issue by btopro** [elmsln/lrnwebcomponents#44]
- when modifying arrays or objects you must tell Polymer exactly what's changed. For example, previously we could do `this.set('items.color', 'blue');` and then if in the HTML there was `[[items.color]]` it would update. This isn't always true. To ensure it updates the template binding, add `this.notifyPath('items.color');` after the set statement. This way polymer knows to refresh template data associated w/ that value
- use px / pixel values as much as possible. em / rem don't behave the way you expect bc of shadow DOM style encapsulation and as such you'll need to set font-size in every element that has anything that has em based values. It's easier to manage just doing everything in px and having multiple sizes for things as needed via class / property changes.
- listeners Removed ability to use id.event to add listeners to elements in shadow DOM. Use declarative template event handlers instead. This means.... that when we've used the listeners object previously, we can't call.. button.tap: _callback. It has to be declared in the attached / detached life cycle hooks. So like this:
```
this.$.audio.addEventListener("ended", this._onEnd());
this.$.audio.removeEventListener("ended", this._onEnd());
```
- slots with names that don't match no longer show up in unnamed slots. example:
```
<cool-thing slot="stuff">whatever</cool-thing>
<slot></slot>
```
The internals of cool-thing MUST define `<slot name="stuff">` or it won't show up. This used to fallback to the unnamed slot area if it wasn't found, now that is not the case in ShadowDom spec.
- `Polymer` global object doesn't exist anymore. So things like `Polymer.dom` won't work. here's some common ones that changed
- `Polymer.dom` becomes `import { dom } from "@polymer/polymer/lib/legacy/polymer.dom.js";` and then calls to it `dom()`
- `this.$$` becomes `this.shadowRoot.querySelector`
- `Polymer.updateStyles` becomes `
import { updateStyles } from '@polymer/polymer/lib/mixins/element-mixin.js';` and then calls to it
`updateStyles();`
- `this.async` becomes `import * as async from "@polymer/polymer/lib/utils/async.js";` and then calls to it via:
```
async.microTask.run(() => {
    });
```
- Polymer object (which these should all be fixed but just saying) are now `import { html, Polymer } from "@polymer/polymer/polymer-legacy.js";`
- Custom style updates have been changed.
```
this.customStyle['--my-dynamic-property'] = 'red';
this.updateStyles();
// After
this.updateStyles({'--my-dynamic-property': 'red'});
```
- anything that pulls in our custom icon libraries needs to include the following to get them to process correctly: `import "@polymer/iron-iconset-svg/iron-iconset-svg.js";`
Commands:
- `yarn start` - at the monorepo level this runs storybook (currently not working). When called inside an element allows you to start doing work on it.
- `yarn run build` - in an element this builds the element to have changes ready for publishing
- `yarn add whatever` - should be run from inside of the element level
- `yarn add @whatever/whatever` - do this *from the element repo you are working on* THEN go to the monorepo level and run `yarn install`. This ensures dependencies are correctly wired across all elements

Other things:
- We are running in full shadow dom, some styling that worked before now will need refactored
- https://www.polymer-project.org/3.0/docs/devguide/style-shadow-dom#share-styles-between-elements should help as a guide to styling
- https://www.polymer-project.org/3.0/docs/upgrade upgrade guide that has largely been implemented but may have some small things not
- Create your own branch to work from and then PR things back in
- Any new workspace names (let's say the element is called @things/new-element) need to be added to the monorepo's nohoist area. (https://github.com/elmsln/lrnwebcomponents/blob/master/package.json#L144-L183)
- All NEW elements will be done in the class based, new way. All changes are made in the whatever-name/src directory and the html, css, js, hax, and properties associated w the element are split into 5 files. The tooling will combine them automatically (`yarn start`) so that you can work on it

Other commands to note.
To upgrade something to Polymer 3 structure that I used to start: `modulizer --out converted --npm-name @lrnwebcomponents/NAMEOFTHETHING --npm-version 0.0.30 --force --import-style name`

Create a new element as a single, scripted command: `wcf element --name=promo-tile --description="My new element I am making" --factory=LOCATIONOFYOURCOMPANY/factories/lrnwebcomponents --customElementTemplate=Polymer --no-useSass --no-addProps --useHAX`

**Comment by btopro** [comment]
@nikkimk @heyMP @cgldevel ^^^

**Comment by craPkit** [comment]
Nice cheat sheet!

Also, `this.fire('event-type', {...detail});` is gone. Instead, use 
```
this.dispatchEvent(new CustomEvent('event-type', {
    bubbles: youDecide,
    composed: true, 
    {...detail}
));
```

**Comment by craPkit** [comment]
`this.debounce('taskName', handler: Function, timeout: Number)` can be replaced with
```
import { Debouncer } from '@polymer/polymer/lib/utils/debounce';
import { timeOut } from '@polymer/polymer/lib/utils/async';
this._debouncer = Debouncer.debounce(this._debouncer,
      timeOut.after(timeout: Number), _handler: Function);
```

**Comment by btopro** [comment]
@craPkit thx for the additions. I tweaked the dispatch event to match the this.fire 1 to 1 replacement (bubbles / cancelable both true).
