### ISSUE TITLE
Check conversion of all behavior/utility-, page-, and application-level components.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/lrnwebcomponents#95]
- [x] hax-body (should break out into own issues, some eco-json-schema data binding and other testing needed to find things and document them outright)
- [x] haxcms-elements (need to do more testing w/ actual integration in system + lrnsys-outline being updated fully)
- [x] responsive-utility
- elmsln-apps (listed here bc they are very specific to elmsln, validation here is simply that they are code ported accurate, not tested in prod environment yet)
  - [x] elmsmedia-dashboard
  - [x] elmsmedia-upload
  - [x] lrnapp-book
  - [x] lrnapp-canvas-listing
  - [x] lrnapp-cis
  - [x] lrnapp-gallery-grid
  - [x] lrnapp-media-grid
  - [x] lrnapp-media-management
  - [x] lrnapp-media-upload
  - [x] lrnapp-open-studio
  - [x] lrnapp-studio-dashboard
  - [x] lrnapp-studio-instructor
  - [x] lrnapp-studio-kanban
  - [x] lrnapp-studio-root
  - [x] lrnapp-studio-submission
  - [x] mooc-content
- [x] a11y-behaviors
- [x] cms-hax
- [x] contenta-polymer (@heyMP do we need this still?)
- [x] hax-body-behaviors
- [x] hax-bookmarklet
- [x] ~~iron-a11y-announcer~~ (we should use polymer version)
- [x] lrn-markdown-editor
- [x] lrnapp-cis
- [x] lrnapp-media-upload
- [x] lrnsys-comment
- [x] materializecss-styles
- [x] media-behaviors
- [x] oer-schema
- [x] schema-behaviors
- [x] simple-colors
- [x] wysiwyg-hax

**Comment by btopro** [comment]
OH SNAP
