### ISSUE TITLE
Syntax error in img-pan-zoom.umd.js

### ISSUE THREAD

**Issue by cosmicdreams** [elmsln/lrnwebcomponents#99]
Tried to check this repo out and execute yarn build.  Actually I tried yarn start but that was, like, running out of memory or something.

So I tried to do something smaller in scope and just run the build task and got this error

```
lerna ERR! yarn run build stderr:

img-pan-zoom.umd.js → img-pan-zoom.umd.js...
[!] (babel plugin) SyntaxError: /Users/cweber/OpenSource/lrnwebcomponents/elements/img-pan-zoom/img-pan-zoom.umd.js: Support for the experimental syntax 'importMeta' isn't currently enabled (167:41):

  165 |   created: function() {
  166 |     const name = "openseadragon";
> 167 |     const basePath = pathFromUrl(import.meta.url);
      |                                         ^
  168 |     const location = `${basePath}lib/openseadragon/build/openseadragon/openseadragon.js`;
  169 |     window.addEventListener(
  170 |       `es-bridge-${name}-loaded`,
```

**Comment by btopro** [comment]
ya `yarn start` is currently not supported by the team as we're still in process of upgrading things. If you want to check out any element all of the individual demos work. You can run `yarn start` from inside of those. For example `cd elements/hexagon-loader && yarn start` to see the one from the video today.

**Comment by btopro** [comment]
A recent commit has resolved this, it was fixed here -- https://github.com/elmsln/lrnwebcomponents/blob/master/scripts/rollup.config.factory.js#L21

This has also been fixed in wcfactory to match
